[SDK][Ruby] Pass origin parameter on attach endpoint
paymongo/paymongo-ruby pull request #21
Opened 2023-08-09 04:11 UTC by scrollloack

What?
-

- Add origin parameter

Why?
-

- To track the usage of our SDK packages by passing origin as param.

Samples/Testing
-

- To follow.

2023-08-09 05:02 UTC, ronilo-penero approved these changes

2023-08-09 05:10 UTC, karlagunday requested changes

2023-08-09 05:10 UTC, karlagunday commented on lib/paymongo/services/payment_intent.rb
> +      payload[:origin] = 'ruby'
This work but I don't recommend mutating the object passed to this function. I would instead do:

```ruby
    def self.attach(id, payload)
      self.request(
        method: :post,
        object: Paymongo::Entities::PaymentIntent,
        path: "#{self::URI}/#{id}/attach",
        payload: payload.merge(origin: 'ruby')
      )
    end
```

2023-08-09 06:43 UTC, karlagunday approved these changes
<img src="https://media4.giphy.com/media/tkApIfibjeWt1ufWwj/giphy.gif"/>

2023-08-10 04:47 UTC, marlon-paymongo approved these changes

2023-08-10 04:48 UTC, ronilo-penero approved these changes

2023-08-10 04:50 UTC, mgfcrespo approved these changes

2023-08-10 04:57 UTC, aleliepangilinan approved these changes

2023-08-10 05:24 UTC, karlagunday approved these changes
<img src="https://media4.giphy.com/media/QVgCZ7EsgfrB9GLcMa/giphy.gif"/>

2023-08-10 07:03 UTC, traqy-paymongo approved these changes

2023-08-17 03:59 UTC, merged